<?php

namespace RobTeifi\Differencer;

class LeftValueMissingResult extends ComparisonResult
{
    private $key;

    public function __construct($depth, $right, $key)
    {
        parent::__construct(false, $depth, null, $right); // TODO: Change the autogenerated stub
        $this->key = $key;
    }

    public static function getMarker()
    {
        return 'LFT';
    }

    /**
     * @return mixed
     */
    public function getKey()
    {
        return $this->key;
    }
}
