<?php

namespace RobTeifi\Differencer;

class MismatchedClassResult extends ComparisonResult
{
    public function __construct($depth, $left, $right)
    {
        parent::__construct(false, $depth, get_class($left), get_class($right)); // TODO: Change the autogenerated stub
    }
}
