<?php

namespace RobTeifi\Differencer;

class NullComparisonResult extends ComparisonResult
{
    public function __construct($matched, $depth)
    {
        parent::__construct($matched, $depth, null, null); // TODO: Change the autogenerated stub
    }
}
