<?php

namespace RobTeifi\Differencer;

class PropertyValueComparisonResult extends KeyValueComparisonResult
{
    public function mapString()
    {
        return ' -> '; // TODO: Change the autogenerated stub
    }
}

 