<?php

namespace RobTeifi\Differencer;

class RightValueMissingResult extends ComparisonResult
{
    private $key;

    public function __construct($depth, $left, $key)
    {
        parent::__construct(false, $depth, $left, null); // TODO: Change the autogenerated stub
        $this->key = $key;
    }

    public static function getMarker()
    {
        return 'RGT';
    }

    /**
     * @return mixed
     */
    public function getKey()
    {
        return $this->key;
    }
}
